name: CI Pipeline

on:
  pull_request:
    branches:
      - dev

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan (dry run)
        run: terraform plan -out=tfplan -input=false

      - name: Security Scan (tfsec)
        uses: aquasecurity/tfsec-action@v1.0.3