name: CI Pipeline

on:
  pull_request:
    branches:
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Create a test terraform.tfvars
        run: cp terraform.tfvars.example terraform.tfvars

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate -var-file=terraform.tfvars

      - name: Terraform Plan (dry run)
        run: terraform plan -out=tfplan -input=false -var-file=terraform.tfvars

      - name: Security Scan (tfsec)
        uses: aquasecurity/tfsec-action@v1.0.3